## Linear Regression

## Part 1 - Data Preprocessing

### Importing the dataset

In [69]:
import pandas as pd
dataset = pd.read_csv('boston.csv')
#importing the dataset using pandas

In [70]:
#dataset
dataset.head(10)

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575   65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421   78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185   61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998   45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147   54.2  6.0622    3  222     18.7   
5  0.02985   0.0   2.18     0  0.458  6.430   58.7  6.0622    3  222     18.7   
6  0.08829  12.5   7.87     0  0.524  6.012   66.6  5.5605    5  311     15.2   
7  0.14455  12.5   7.87     0  0.524  6.172   96.1  5.9505    5  311     15.2   
8  0.21124  12.5   7.87     0  0.524  5.631  100.0  6.0821    5  311     15.2   
9  0.17004  12.5   7.87     0  0.524  6.004   85.9  6.5921    5  311     15.2   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2  
5  394.12   5.21  28.7  
6  395.60  12.43  22.9  
7  396.90  19.15  27.1  
8  386.63  29.93  16.5  
9  386.71  17.10  18.9

In [71]:
#inspection of the data
#CRIM per capita crime rate by town
#ZN proportion of residential land zoned for lots over 25,000 sq.ft.
#INDUS proportion of non-retail business acres per town
#CHAS Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
#NOX nitric oxides concentration (parts per 10 million)
#RM average number of rooms per dwelling
#AGE proportion of owner-occupied units built prior to 1940
#DIS weighted distances to five Boston employment centres
#RAD index of accessibility to radial highways
#TAX full-value property-tax rate per 10,000usd
#PTRATIO pupil-teacher ratio by town
#B 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
#LSTAT % lower status of the population

#Each record in the database describes a Boston suburb or town.
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64  
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    int64  
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [72]:
#description of the data, what are the maximum and minimum
dataset.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [73]:
#no columns that have missing values
dataset.isna().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [74]:
#The columns in the dataset
dataset.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [75]:
#The dataset have 506 rows and 14 columns
dataset.shape

(506, 14)

### Getting the inputs and output

In [76]:
# [rows,columns]
X = dataset.iloc[:,:-1].values
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [77]:
y = dataset.iloc[:,-1].values
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [78]:
# Create polynomial features manually

import numpy as np

X = np.column_stack((
    X,
    X[:, 5]**2,  # RM squared
    X[:, 12]**2,  # LSTAT squared
    X[:, 5] * X[:, 12]  # RM * LSTAT interaction
))

### Creating the Training Set and the Test Set

In [79]:
# scikitlearn is a library
# model_selection is a module
# train_test_split is a function
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.1, random_state=42)

In [80]:
X_train

array([[3.7050000e-02, 2.0000000e+01, 3.3300000e+00, ..., 4.8553024e+01,
        2.1068100e+01, 3.1983120e+01],
       [1.2324700e+00, 0.0000000e+00, 8.1400000e+00, ..., 3.7724164e+01,
        3.5043840e+02, 1.1497824e+02],
       [1.1432000e-01, 0.0000000e+00, 8.5600000e+00, ..., 4.5981961e+01,
        5.8828900e+01, 5.2010270e+01],
       ...,
       [1.5010000e-02, 8.0000000e+01, 2.0100000e+00, ..., 4.4023225e+01,
        3.5880100e+01, 3.9743650e+01],
       [1.1160400e+01, 0.0000000e+00, 1.8100000e+01, ..., 4.3943641e+01,
        5.4149290e+02, 1.5425683e+02],
       [2.2876000e-01, 0.0000000e+00, 8.5600000e+00, ..., 4.1024025e+01,
        1.1299690e+02, 6.8085150e+01]])

In [81]:
X_test

array([[9.1780000e-02, 0.0000000e+00, 4.0500000e+00, 0.0000000e+00,
        5.1000000e-01, 6.4160000e+00, 8.4100000e+01, 2.6463000e+00,
        5.0000000e+00, 2.9600000e+02, 1.6600000e+01, 3.9550000e+02,
        9.0400000e+00, 4.1165056e+01, 8.1721600e+01, 5.8000640e+01],
       [5.6440000e-02, 4.0000000e+01, 6.4100000e+00, 1.0000000e+00,
        4.4700000e-01, 6.7580000e+00, 3.2900000e+01, 4.0776000e+00,
        4.0000000e+00, 2.5400000e+02, 1.7600000e+01, 3.9690000e+02,
        3.5300000e+00, 4.5670564e+01, 1.2460900e+01, 2.3855740e+01],
       [1.0574000e-01, 0.0000000e+00, 2.7740000e+01, 0.0000000e+00,
        6.0900000e-01, 5.9830000e+00, 9.8800000e+01, 1.8681000e+00,
        4.0000000e+00, 7.1100000e+02, 2.0100000e+01, 3.9011000e+02,
        1.8070000e+01, 3.5796289e+01, 3.2652490e+02, 1.0811281e+02],
       [9.1640000e-02, 0.0000000e+00, 1.0810000e+01, 0.0000000e+00,
        4.1300000e-01, 6.0650000e+00, 7.8000000e+00, 5.2873000e+00,
        4.0000000e+00, 3.0500000e+02, 1.92000

In [82]:
y_train

array([35.4, 15.2, 26.5, 43.5, 21.2, 18.4, 28.5, 23.9, 18.5, 25. , 35.4,
       31.5, 20.2, 24.1, 20. , 13.1, 24.8, 30.8, 12.7, 20. , 23.7, 10.8,
       20.6, 20.8,  5. , 20.1, 48.5, 10.9,  7. , 20.9, 17.2, 20.9,  9.7,
       19.4, 29. , 16.4, 25. , 25. , 17.1, 23.2, 10.4, 19.6, 17.2, 27.5,
       23. , 50. , 17.9,  9.6, 17.2, 22.5, 21.4, 12. , 19.9, 19.4, 13.4,
       18.2, 24.6, 21.1, 24.7,  8.7, 27.5, 20.7, 36.2, 31.6, 11.7, 39.8,
       13.9, 21.8, 23.7, 17.6, 24.4,  8.8, 19.2, 25.3, 20.4, 23.1, 37.9,
       15.6, 45.4, 15.7, 22.6, 14.5, 18.7, 17.8, 16.1, 20.6, 31.6, 29.1,
       15.6, 17.5, 22.5, 19.4, 19.3,  8.5, 20.6, 17. , 17.1, 14.5, 50. ,
       14.3, 12.6, 28.7, 21.2, 19.3, 23.1, 19.1, 25. , 33.4,  5. , 29.6,
       18.7, 21.7, 23.1, 22.8, 21. , 48.8, 14.6, 16.6, 27.1, 20.1, 19.8,
       21. , 41.3, 23.2, 20.4, 18.5, 29.4, 36.4, 24.4, 11.8, 13.8, 12.3,
       17.8, 33.1, 26.7, 13.4, 14.4, 50. , 22. , 19.9, 23.8, 17.5, 12.7,
        5.6, 31.1, 26.2, 19.4, 16.7, 13.8, 22.9, 15

In [83]:
y_test

array([23.6, 32.4, 13.6, 22.8, 16.1, 20. , 17.8, 14. , 19.6, 16.8, 21.5,
       18.9,  7. , 21.2, 18.5, 29.8, 18.8, 10.2, 50. , 14.1, 25.2, 29.1,
       12.7, 22.4, 14.2, 13.8, 20.3, 14.9, 21.7, 18.3, 23.1, 23.8, 15. ,
       20.8, 19.1, 19.4, 34.7, 19.5, 24.4, 23.4, 19.7, 28.2, 50. , 17.4,
       22.6, 15.1, 13.1, 24.2, 19.9, 24. , 18.9])

In [84]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## Part 2 - Building and training the model

### Building the model

In [85]:
# linear_model is the module
# LinearRegression is a class, it contains a pre-coded blueprint on how to build a linear regression model
# Class is a pre-coded blueprint of something we want to build from which objects are created.
from sklearn.linear_model import LinearRegression
model = LinearRegression()

### Training the Model

In [86]:
# fit is a method inside LinearRegression class - they are like functions.
model.fit(X_train, y_train)

LinearRegression()

In [87]:
model.intercept_

np.float64(93.44865414177079)

### Inference

In [88]:
y_pred = model.predict(X_test)
y_pred

array([27.52493768, 36.11631693, 13.3560484 , 25.69161414, 16.57645571,
       21.93675103, 16.11201633, 12.30534757, 22.00083076, 18.77320033,
       22.07948838, 17.11377151,  8.86262273, 20.24694862, 19.72709317,
       24.45725586, 19.36903113, 12.90297179, 43.74105128, 15.49957516,
       26.53485959, 28.6465744 , 11.7483622 , 23.02782493, 16.87365303,
       16.88039275, 22.53478576, 13.70439192, 20.35063878, 18.05672287,
       21.59403962, 25.32587454, 23.42174975, 20.16088856, 15.63603889,
       16.13443881, 33.62307468, 20.35485571, 21.23681226, 24.07450498,
       14.30693239, 31.34347666, 46.4790286 , 17.37686258, 25.89129743,
       16.47350449, 14.21276939, 25.54237326, 18.51521753, 30.06353719,
       20.15127902])

## Part 3: Evaluating the Model

### R-Squared

In [89]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
r2

0.8774370925197137

### Adjusted R-Squared

In [90]:
k = X_test.shape[1]
k

16

In [91]:
n = X_test.shape[0]
n

51

In [98]:
adj_r2 = 1-(1-r2)*(n-1)/(n-k-1)
adj_r2

0.8197604301760495

### Mean Squared Error

In [100]:
mse = np.mean((y_test - y_pred) ** 2)
mse

np.float64(7.652119236368388)